### ISSUE TITLE
Performance tips 

### ISSUE THREAD

**Issue by kevinburkesegment** [tailscale/go-cache-plugin#10]
After probably a day of recompiling Go 1.23, updating build configurations, ensuring that the cache was being hit, etc, I was disappointed to find that we didn't get any performance improvement from using S3 as a backend. We are in AWS already using Buildkite, when I turn on debug mode, the typical S3 latency is around 10-50ms, usually closer to ten though. 

I know this is not code related and feel free to close, but I'm wondering if there are any specific performance related strategies you did to get a speedup from using this library, for example, find a way to persist the disk cache between runs, or use a separate disk cache _and_ S3 in parallel. One thing I did do was turn off `-p 1` which was enabled by default for our system, that helped a little but not a lot.

**Comment by creachadair** [comment]
I don't have specific advice, the main benefit I've observed is for cold start on a fresh builder, at steady-state it looks similar in performance to a purely local cache. It's worth noting that the tool already _does_ use a disk cache (this is actually required by the design, since the Go toolchain needs physical disk paths as responses from the cache, so things fetched from S3 are cached locally anyway).

Even with this in place, cold start is not as good as I'd have liked. Enabling the module and sumdb cache does help quite a bit in our configuration, but it's not going to erase the cost of warming up the local files.

Bumping up the task concurrency should help—I am running with `-c 512` and `-u 48` which mostly averts S3 rate limits but keeps the compiler as busy as I/O will allow. If your workers use EBS for their root disk, bumping up the iops can help somewhat too. In practice, it helped our cold start time quite a bit. Putting the local caches on a fast NVMe disk might help too (and it could even be ephemeral, since that's cheaper).

One of the annoying limitations of the plugin protocol is that the toolchain does not currently cache test results, nor does it cache _any_ linker outputs. That's not something we can fix in the plugin—those are limitations of the way the toolchain speaks to it. I have hope those may get improved in the future.

**Comment by kevinburkesegment** [comment]
Really appreciate this. I did not know GOCACHEPROG did not support test result caching, though in our case we run everything with code coverage on which defeats that cache anyway. Thank you! I'll try increasing the task concurrency and see if we get better results.

**Comment by kevinburkesegment** [comment]
Going to close this, I'll reopen if I have specific questions

**Comment by bradfitz** [comment]
> One of the annoying limitations of the plugin protocol is that the toolchain does not currently cache test results

That's not true. There's nothing in the protocol explicitly for it, but it uses the same object/action cache for tests as it does for binary outputs.

Observe:

```
bradfitz@book1pro tailscale.com % GOCACHEPROG="$HOME/go/bin/go-cacher --verbose" ./tool/go test -v ./util/lineiter
2024/12/07 11:00:44 Defaulting to cache dir /Users/bradfitz/Library/Caches/go-cacher ...
=== RUN   TestBytesLines
--- PASS: TestBytesLines (0.00s)
=== RUN   TestReader
--- PASS: TestReader (0.00s)
PASS
ok  	tailscale.com/util/lineiter	0.004s
2024/12/07 11:00:47 cacher: closing; 259 gets (52 hits, 207 misses, 0 errors); 402 puts (0 errors)


bradfitz@book1pro tailscale.com % GOCACHEPROG="$HOME/go/bin/go-cacher --verbose" ./tool/go test -v ./util/lineiter
2024/12/07 11:00:50 Defaulting to cache dir /Users/bradfitz/Library/Caches/go-cacher ...
=== RUN   TestBytesLines
--- PASS: TestBytesLines (0.00s)
=== RUN   TestReader
--- PASS: TestReader (0.00s)
PASS
ok  	tailscale.com/util/lineiter	(cached)
2024/12/07 11:00:50 cacher: closing; 421 gets (421 hits, 0 misses, 0 errors); 1 puts (0 errors)
```

The cache works for tests.
